### ISSUE TITLE
Ambiguous definition of "object-observe-api" in features.js

### ISSUE THREAD

**Issue by harbalk** [ibm-js/liaison#156]
Examining the source code of ObservableArray.js, I noticed an ambiguous definition of the feature "object-observe-api".
Shouldn't have been better to create separated features for "object-observe-api" and "array-observe-api" in feature.js ?
When reading the code in ObservableArray.js we could understand that some browsers don't have observable object at all but in fact they just don't have the new Array.observe functionality.
Tell me what you think about it.

**Comment by asudoh** [comment]
Hi @harbalk thank you for sharing your thoughts and sorry for late response, `has(“object-observe-api”)` are for checking existence of ES7 `Object.observe()` and `Array.observe()` APIs, which Chrome 36 (IIRC) introduced. I think when a browser introduces one there is no reason not to introduce another, that’s why I made `has(“object-observe-api”)` to catch both. Tell me what you think.

**Comment by harbalk** [comment]
Yes you are probably right, it was not evident to me but the case where the browser has just one of the two features will surely not be reached in use case.

**Comment by asudoh** [comment]
OK closing as such, thanks @harbalk for your feedback.
