### ISSUE TITLE
Operation not recognized by ObservableArray

### ISSUE THREAD

**Issue by harbalk** [ibm-js/liaison#157]
I found an operation not recognized by ObservableArray on browsers which don't have Array Observe Api.

On Google Chrome, operations as "observableArr[0] = arr1[0]" is observed but not on firefox and other browsers.

I didn't find a solution for now.

**Comment by asudoh** [comment]
You'll need to use `set()` API to stamp out change records for observation. In this particular case `observaeArr.set(0, arr1[0])`.

**Comment by asudoh** [comment]
Made change to README.md to make it clearer: https://github.com/ibm-js/liaison/pull/158/files#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by harbalk** [comment]
Yes I understand I have to use the function set().
But it should be clearer for the user that he can not use "observableArr[0] = arr1[0]" with our implementation because it is different from the examples here : https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/observe .

**Comment by asudoh** [comment]
Right it’s different from how ES7 `Array.observe()` works in that part, which is, you’ll need explicit way to notify changes with `ObservableArray.observe()` if ES7 `Array.observe()` does *not* exist in your browser.

Made further updates to documents:
https://github.com/ibm-js/liaison/commit/438c6aa6f887da628167dcc3aa0b72b9ea4a7513
https://github.com/ibm-js/liaison/commit/0ef9cccca2f361009f5dd85ca9b99a9051258a47
