### ISSUE TITLE
Attach points are not getting attached in my template

### ISSUE THREAD

**Issue by kgibb** [ibm-js/liaison#166]
I've given a widget in my template an attach point but it's not getting attached to the parent widget. 

```
<template bind="{{model}}" >
...
<d-slider data-attach-point="slider" value="{{progress}}" step="1" min="0" max="100" ></d-slider>
...
</template>
```
I load the template through the requirejs-text plugin and pass it into the createRenderer module. The this.querySelectorAll("[data-attach-point]") call in createRenderer.js is returning empty.

**Comment by asudoh** [comment]
`<template>` is inert until the content is stamped out. For data-bound template data binding engine (liaison, Polymer TemplateBinding library, etc.) tends to do that as data binding happens, but for other cases it doesn't happens unless somebody explicitly does that. So it's hard for a widget to search for an element with data-attach-point inside `<template>`.
For the record, http://jsfiddle.net/x7u0ebzr/ further explains what @kgibb reported.
