### ISSUE TITLE
remove liaison/ObservableArray, use decor/ObservableArray

### ISSUE THREAD

**Issue by wkeese** [ibm-js/liaison#170]
@harbalk copied ObservableArray to decor in ibm-js/decor@c9429f0b1b0f092f774f96c40153d3bcefb79e60, so you should remove it (including tests and doc) from liaison, and switch liaison to use the one in decor.

**Comment by asudoh** [comment]
Documentation part is tracked in a separate issue: https://github.com/ibm-js/liaison/issues/173
